version: '3.8'

services:
  postgres:
    build: .
    container_name: personal_finances_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: personal_finances
      POSTGRES_USER: finance_user
      POSTGRES_PASSWORD: finance_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - personal_finances_network

volumes:
  postgres_data:

networks:
  personal_finances_network:
    driver: bridge