"""Update description field in categories table lenghtss

Revision ID: 257107dfdf79
Revises: 9bef6a85d7fb
Create Date: 2025-10-23 00:09:24.099505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '257107dfdf79'
down_revision: Union[str, Sequence[str], None] = '9bef6a85d7fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=270),
               type_=sa.String(length=280),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.String(length=280),
               type_=sa.VARCHAR(length=270),
               existing_nullable=False)

    # ### end Alembic commands ###
