"""Update description field in categories table lenght

Revision ID: 9bef6a85d7fb
Revises: d5f28caedc34
Create Date: 2025-10-23 00:08:15.605110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bef6a85d7fb'
down_revision: Union[str, Sequence[str], None] = 'd5f28caedc34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
