"""change description for item in daily_finances table, add payment method field

Revision ID: f2b2017e81d1
Revises: 68d9a2dc6baf
Create Date: 2025-10-23 01:23:56.116973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2b2017e81d1'
down_revision: Union[str, Sequence[str], None] = '68d9a2dc6baf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_finances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item', sa.String(length=280), nullable=True))
        batch_op.add_column(sa.Column('payment_method', sa.String(length=50), nullable=True))
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_finances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=280), nullable=True))
        batch_op.drop_column('payment_method')
        batch_op.drop_column('item')

    # ### end Alembic commands ###
